// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
 
package com.scouting.config;

import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.concurrent.TimeUnit;

/**
 * Questa classe è un miglioramento della "User Experience" (UX).
 * In un'applicazione Web locale, è scomodo per l'utente dover aprire manualmente il browser e digitare "localhost:8080".
 * Questa classe ascolta l'evento di "Applicazione Pronta" e tenta di aprire automaticamente la pagina corretta.
 *
 * Dal punto di vista tecnico, utilizza una strategia euristica: prima prova le API Java Desktop standard;
 * se falliscono (comune su alcuni server o container), prova a eseguire comandi nativi del sistema operativo
 * (Windows, Mac, Linux) per garantire l'apertura.
 */

@Component
public class BrowserLauncher {

    private static final Logger logger = LoggerFactory.getLogger(BrowserLauncher.class);
    private static final String URL = "http://localhost:8080";

    @EventListener(ApplicationReadyEvent.class)
    public void launchBrowserStrategy() {
        new Thread(() -> {
            try {
                TimeUnit.SECONDS.sleep(2);
                
                logger.info("Tentativo di apertura automatica del browser a: {}", URL);

                boolean javaDesktopSuccess = attemptJavaDesktopOpen();

                if (!javaDesktopSuccess) {
                    attemptOsCommandOpen();
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    private boolean attemptJavaDesktopOpen() {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(URL));
                logger.info("Browser aperto tramite Java Desktop API.");
                return true;
            }
        } catch (Exception e) {
            logger.warn("Java Desktop API fallita (normale se da terminale), passo al metodo OS...");
        }
        return false;
    }

    private void attemptOsCommandOpen() {
        String os = System.getProperty("os.name").toLowerCase();
        ProcessBuilder builder = null;

        try {
            if (os.contains("win")) {
                builder = new ProcessBuilder("rundll32", "url.dll,FileProtocolHandler", URL);
            } else if (os.contains("mac")) {
                builder = new ProcessBuilder("open", URL);
            } else if (os.contains("nix") || os.contains("nux")) {
                builder = new ProcessBuilder("xdg-open", URL);
            }

            if (builder != null) {
                builder.start();
                logger.info("Browser aperto tramite comando OS nativo.");
            } else {
                logger.error("Impossibile determinare il comando OS per aprire il browser.");
            }
        } catch (IOException e) {
            logger.error("Fallimento totale apertura browser: {}", e.getMessage());
            logger.info(">>> APRI QUESTO LINK MANUALMENTE: {} <<<", URL);
        }
    }
}