// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.scouting.service;

import com.scouting.data.model.Player;
import com.scouting.data.repository.PlayerRepository;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class ScoutingService {
    
    private final PlayerRepository playerRepository;
    
    public ScoutingService(PlayerRepository playerRepository) {
        this.playerRepository = playerRepository;
    }
    
    // US-02: Fornire lista completa
    public List<Player> getAllPlayers() {
        return playerRepository.findAll();
    }
}