// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.scouting.UI;

import com.scouting.data.model.Player;
import com.scouting.service.ScoutingService;
import com.vaadin.flow.component.combobox.MultiSelectComboBox;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

import java.util.*;

@Route("")
public class MainView extends VerticalLayout {
    
    private final ScoutingService scoutingService;
    private final Grid<Player> grid;
    private final Span recordCount;
    private final List<Player> allPlayers;
    
    private MultiSelectComboBox<String> columnSelector;
    private Map<String, Runnable> columnConfigurations;
    
    public MainView(ScoutingService scoutingService) {
        this.scoutingService = scoutingService;
        this.allPlayers = scoutingService.getAllPlayers();
        
        setSizeFull(); 
        setPadding(true);
        setSpacing(true);
        
        add(new H1("Football Player Scouting Suite (2025-26)"));
        
        grid = new Grid<>(Player.class, false);
        grid.setSizeFull(); 
        
        initializeColumnConfigurations();
        
        createToolbar();
        
        // Default View
        configureDefaultColumns();
        
        recordCount = new Span();
        recordCount.getStyle().set("font-weight", "bold");
        updateRecordCount();
        
        add(columnSelector, recordCount, grid);
        
        expand(grid); 
        
        grid.setItems(allPlayers);
        
        System.out.println("MainView inizializzata. Righe caricate: " + allPlayers.size());
    }
    
    private void createToolbar() {
        columnSelector = new MultiSelectComboBox<>("Seleziona Metriche (US-03)");
        columnSelector.setItems(columnConfigurations.keySet());
        columnSelector.select("Basic Info"); // Selezione default
        columnSelector.setWidth("100%");
        columnSelector.setMaxWidth("600px");
        columnSelector.setPlaceholder("Scegli categorie statistiche...");
        columnSelector.addValueChangeListener(e -> updateColumnVisibility());
    }
    
    private void initializeColumnConfigurations() {
        columnConfigurations = new LinkedHashMap<>();

        columnConfigurations.put("Basic Info", () -> {
            grid.addColumn(Player::getName).setHeader("Player").setFrozen(true).setWidth("180px").setSortable(true).setResizable(true);
            grid.addColumn(Player::getAge).setHeader("Age").setWidth("70px").setSortable(true);
            grid.addColumn(Player::getPosition).setHeader("Position").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getSquad).setHeader("Squad").setWidth("150px").setSortable(true).setResizable(true);
            grid.addColumn(Player::getNation).setHeader("Nation").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getCompetition).setHeader("Competition").setWidth("150px").setSortable(true).setResizable(true);
        });

        columnConfigurations.put("Playing Time", () -> {
            grid.addColumn(Player::getMatches).setHeader("Matches").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getStarts).setHeader("Starts").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getMinutes).setHeader("Minutes").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getNinetyS())).setHeader("90s").setWidth("80px").setSortable(true);
        });

        columnConfigurations.put("Standard Attacking", () -> {
            grid.addColumn(Player::getGoals).setHeader("Goals").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getAssists).setHeader("Assists").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getgPlusA).setHeader("G+A").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getNpg).setHeader("Non-Pen Goals").setWidth("130px").setSortable(true);
            grid.addColumn(Player::getPkMade).setHeader("PK Made").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getPkAttempted).setHeader("PK Att").setWidth("100px").setSortable(true);
        });

        columnConfigurations.put("Shooting", () -> {
            grid.addColumn(Player::getShots).setHeader("Shots").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getSot).setHeader("SoT").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getSotPercentage())).setHeader("SoT%").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getgPerShots())).setHeader("G/Sh").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getgPerSot())).setHeader("G/SoT").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getAvgShotDist())).setHeader("Avg Dist").setWidth("110px").setSortable(true);
        });

        columnConfigurations.put("Expected Metrics (xG)", () -> {
            grid.addColumn(p -> fmt(p.getXg())).setHeader("xG").setWidth("80px").setSortable(true);
            grid.addColumn(p -> fmt(p.getNpxg())).setHeader("npxG").setWidth("80px").setSortable(true);
            grid.addColumn(p -> fmt(p.getXag())).setHeader("xAG").setWidth("80px").setSortable(true);
            grid.addColumn(p -> fmt(p.getNpxgPlusXag())).setHeader("npxG+xAG").setWidth("110px").setSortable(true);
            grid.addColumn(p -> fmt(p.getgMinusXg())).setHeader("G-xG").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getNpgMinusXg())).setHeader("npG-xG").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getaMinusXag())).setHeader("A-xAG").setWidth("90px").setSortable(true);
        });
        
        columnConfigurations.put("Passing", () -> {
            grid.addColumn(Player::getPassesCompleted).setHeader("Pass Cmp").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getPassesAttempted).setHeader("Pass Att").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getPassesPercentage())).setHeader("Pass %").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getKeyPasses).setHeader("Key Passes").setWidth("110px").setSortable(true);
            grid.addColumn(Player::getPassesFinalThird).setHeader("Pass Final 3rd").setWidth("130px").setSortable(true);
            grid.addColumn(Player::getPassesPenArea).setHeader("Pass Pen Area").setWidth("130px").setSortable(true);
            grid.addColumn(Player::getCrossesPenArea).setHeader("Cross Pen Area").setWidth("130px").setSortable(true);
        });
        
        columnConfigurations.put("Progressive Play", () -> {
            grid.addColumn(Player::getProgCarries).setHeader("Prog Carries").setWidth("120px").setSortable(true);
            grid.addColumn(Player::getProgPasses).setHeader("Prog Passes").setWidth("120px").setSortable(true);
            grid.addColumn(Player::getProgPassesReceived).setHeader("Prog Rec").setWidth("120px").setSortable(true);
        });
        
        columnConfigurations.put("Possession & Dribbling", () -> {
            grid.addColumn(Player::getTouches).setHeader("Touches").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getTakeOnAttempted).setHeader("Dribble Att").setWidth("110px").setSortable(true);
            grid.addColumn(Player::getTakeOnSucc).setHeader("Dribble Succ").setWidth("110px").setSortable(true);
            grid.addColumn(p -> fmt(p.getTakeOnPercentage())).setHeader("Dribble %").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getCarries).setHeader("Carries").setWidth("100px").setSortable(true);
            grid.addColumn(Player::getDispossessed).setHeader("Dispossessed").setWidth("120px").setSortable(true);
            grid.addColumn(Player::getMiscontrols).setHeader("Miscontrols").setWidth("110px").setSortable(true);
        });

        columnConfigurations.put("Defensive Actions", () -> {
            grid.addColumn(Player::getTackles).setHeader("Tackles").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getTacklesWon).setHeader("Tkl Won").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getTacklesPercentage())).setHeader("Tkl %").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getInterceptions).setHeader("Int").setWidth("80px").setSortable(true);
            grid.addColumn(Player::getTklPlusInt).setHeader("Tkl+Int").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getBlocks).setHeader("Blocks").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getClearances).setHeader("Clear").setWidth("90px").setSortable(true);
            grid.addColumn(Player::getErrorsLeadingShot).setHeader("Errors").setWidth("90px").setSortable(true);
        });

        columnConfigurations.put("Goal & Shot Creation", () -> {
            grid.addColumn(Player::getSca).setHeader("SCA").setWidth("80px").setSortable(true);
            grid.addColumn(Player::getGca).setHeader("GCA").setWidth("80px").setSortable(true);
        });

        columnConfigurations.put("Per 90 (Attacking)", () -> {
            grid.addColumn(p -> fmt(p.getGoalsP90())).setHeader("Goals/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getAssistsP90())).setHeader("Assists/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getgPlusAP90())).setHeader("G+A/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getNpgP90())).setHeader("npg/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getXgP90())).setHeader("xG/90").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getXagP90())).setHeader("xAG/90").setWidth("90px").setSortable(true);
        });

        columnConfigurations.put("Per 90 (General Play)", () -> {
            grid.addColumn(p -> fmt(p.getShotsP90())).setHeader("Shots/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getSotP90())).setHeader("SoT/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getKeyPassesP90())).setHeader("Key Pass/90").setWidth("120px").setSortable(true);
            grid.addColumn(p -> fmt(p.getProgCarriesP90())).setHeader("Prog Carr/90").setWidth("120px").setSortable(true);
            grid.addColumn(p -> fmt(p.getProgPassesP90())).setHeader("Prog Pass/90").setWidth("120px").setSortable(true);
            grid.addColumn(p -> fmt(p.getTouchesP90())).setHeader("Touches/90").setWidth("110px").setSortable(true);
        });
        
        columnConfigurations.put("Per 90 (Defensive)", () -> {
            grid.addColumn(p -> fmt(p.getTacklesP90())).setHeader("Tkl/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getInterceptionsP90())).setHeader("Int/90").setWidth("90px").setSortable(true);
            grid.addColumn(p -> fmt(p.getClearancesP90())).setHeader("Clear/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getBlocksP90())).setHeader("Blocks/90").setWidth("100px").setSortable(true);
            grid.addColumn(p -> fmt(p.getRecoveriesP90())).setHeader("Recov/90").setWidth("110px").setSortable(true);
        });
    }
    
    private void configureDefaultColumns() {
        grid.removeAllColumns();
        List.of("Basic Info", "Playing Time", "Standard Attacking", "Shooting", 
                "Expected Metrics (xG)", "Passing", "Progressive Play", 
                "Possession & Dribbling", "Defensive Actions", "Goal & Shot Creation", 
                "Per 90 (Attacking)", "Per 90 (General Play)", "Per 90 (Defensive)")
            .forEach(key -> {
                if(columnConfigurations.containsKey(key)) {
                    columnConfigurations.get(key).run();
                }
            });
    }
    
    private void updateColumnVisibility() {
        grid.removeAllColumns();
        var selected = columnSelector.getSelectedItems();
        
        if (selected.isEmpty()) {
            configureDefaultColumns();
        } else {
            // Mantiene l'ordine di inserimento della mappa (Basic Info prima)
            columnConfigurations.forEach((key, config) -> {
                if (selected.contains(key)) {
                    config.run();
                }
            });
        }
    }
    
    private void updateRecordCount() {
        recordCount.setText("Visualizzando %d giocatori (Database 2025-26)".formatted(allPlayers.size()));
    }
    
    private String fmt(Double value) {
        return value != null ? "%.2f".formatted(value) : "-";
    }
}