// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
 
package com.scouting.data.model;

import jakarta.persistence.*;

/**
 * Questa classe rappresenta l'entità fondamentale del nostro "Universo del Discorso": il Calciatore.
 * In un'architettura Enterprise come questa, funge da <strong>Domain Model</strong>.
 * <p>
 * Tecnicamente, è un semplice <strong>POJO (Plain Old Java Object)</strong>, ovvero un oggetto Java puro senza
 * logica complessa, che però viene "potenziato" dalle annotazioni <strong>JPA (Java Persistence API)</strong>.
 * Le annotazioni come <code>@Entity</code> e <code>@Table</code> istruiscono il framework Hibernate su come
 * trasformare (Mapping) le istanze di questa classe in righe della tabella del database e viceversa.
 * <p>
 * Dal punto di vista del design, adottiamo un "Anemic Domain Model": questa classe contiene solo i dati (statistiche,
 * anagrafica) e i metodi di accesso (Getter/Setter), delegando interamente la logica di business e di calcolo
 * al Service Layer. Nelle metriche software, questo componente rappresenta solitamente una "foglia" dell'albero
 * delle dipendenze: è utilizzato da quasi tutti gli altri layer (Repository, Service, UI), ma lui non dipende
 * da nessuno di essi, garantendo la portabilità dei dati.
 */

@Entity
@Table(name = "player")
public class Player {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private Integer age;
    private String nation;
    private String position;
    private String squad;
    private String competition;
    private Integer matches;
    private Integer starts;
    private Integer minutes;
    @Column(name = "nineties")
    private Double ninetyS; // 90s
    private Integer goals;
    private Integer assists;
    @Column(name = "g_plus_a")
    private Integer gPlusA; // G+A
    @Column(name = "pk_made")
    private Integer pkMade;
    @Column(name = "pk_attempted")
    private Integer pkAttempted;
    @Column(name = "yellow_cards")
    private Integer yellowCards;
    @Column(name = "red_cards")
    private Integer redCards;
    private Double xg;
    private Double npxg;
    private Double xag;
    @Column(name = "npxg_plus_xag")
    private Double npxgPlusXag; // npxG+xAG
    @Column(name = "prog_carries")
    private Integer progCarries;
    @Column(name = "prog_passes")
    private Integer progPasses;
    @Column(name = "prog_passes_received")
    private Integer progPassesReceived;
    @Column(name = "xg_plus_xag")
    private Double xgPlusXag; // xG+xAG
    @Column(name = "avg_shot_dist")
    private Double avgShotDist;
    @Column(name = "g_minus_xg")
    private Double gMinusXg; // G-xG
    @Column(name = "g_per_shots")
    private Double gPerShots; // G/Shots
    @Column(name = "g_per_sot")
    private Double gPerSot; // G/SoT
    private Integer shots;
    private Integer sot;
    @Column(name = "sot_percentage")
    private Double sotPercentage; // SoT%
    @Column(name = "npg_minus_xg")
    private Double npgMinusXg; // npG-xG
    @Column(name = "npxg_per_shots")
    private Double npxgPerShots; // npxG/Shots
    @Column(name = "passes_final_third")
    private Integer passesFinalThird;
    @Column(name = "a_minus_xag")
    private Double aMinusXag; // A-xAG
    @Column(name = "passes_attempted")
    private Integer passesAttempted;
    @Column(name = "take_on_attempted")
    private Integer takeOnAttempted;
    @Column(name = "passes_completed")
    private Integer passesCompleted;
    @Column(name = "passes_percentage")
    private Double passesPercentage;
    @Column(name = "crosses_pen_area")
    private Integer crossesPenArea;
    @Column(name = "key_passes")
    private Integer keyPasses;
    @Column(name = "passes_pen_area")
    private Integer passesPenArea;
    @Column(name = "tot_dist_prg_passes")
    private Double totDistPrgPasses;
    @Column(name = "tot_dist_passes")
    private Double totDistPasses;
    private Integer blocks;
    @Column(name = "corner_kicks")
    private Integer cornerKicks;
    private Integer crosses;
    private Integer offsides;
    private Integer switches;
    @Column(name = "through_balls")
    private Integer throughBalls;
    @Column(name = "throw_ins")
    private Integer throwIns;
    private Integer fouled;
    private Integer gca;
    private Integer sca;
    @Column(name = "tackles_att_3rd")
    private Integer tacklesAtt3rd;
    private Integer clearances;
    @Column(name = "tackles_def_3rd")
    private Integer tacklesDef3rd;
    @Column(name = "errors_leading_shot")
    private Integer errorsLeadingShot;
    private Integer interceptions;
    @Column(name = "challenges_lost")
    private Integer challengesLost;
    @Column(name = "tackles_mid_3rd")
    private Integer tacklesMid3rd;
    private Integer tackles;
    @Column(name = "tackles_percentage")
    private Double tacklesPercentage;
    @Column(name = "tkl_plus_int")
    private Integer tklPlusInt;
    @Column(name = "tackles_won")
    private Integer tacklesWon;
    @Column(name = "touches_att_pen")
    private Integer touchesAttPen;
    @Column(name = "carries_pen_area")
    private Integer carriesPenArea;
    private Integer carries;
    @Column(name = "touches_def_pen")
    private Integer touchesDefPen;
    private Integer dispossessed;
    private Integer miscontrols;
    @Column(name = "passes_received")
    private Integer passesReceived;
    @Column(name = "take_on_succ")
    private Integer takeOnSucc;
    @Column(name = "take_on_percentage")
    private Double takeOnPercentage;
    private Integer touches;
    @Column(name = "second_yellow")
    private Integer secondYellow;
    private Integer fouls;
    @Column(name = "own_goal")
    private Integer ownGoal;
    @Column(name = "pk_conceded")
    private Integer pkConceded;
    @Column(name = "pk_won")
    private Integer pkWon;
    private Integer recoveries;
    @Column(name = "aerial_won")
    private Integer aerialWon;
    @Column(name = "aerial_won_percentage")
    private Double aerialWonPercentage;
    private Integer npg;
    @Column(name = "goals_p90")
    private Double goalsP90;
    @Column(name = "assists_p90")
    private Double assistsP90;
    @Column(name = "g_plus_a_p90")
    private Double gPlusAP90;
    @Column(name = "npg_p90")
    private Double npgP90;
    @Column(name = "xg_p90")
    private Double xgP90;
    @Column(name = "npxg_p90")
    private Double npxgP90;
    @Column(name = "xag_p90")
    private Double xagP90;
    @Column(name = "npxg_plus_xag_p90")
    private Double npxgPlusXagP90;
    @Column(name = "xg_plus_xag_p90")
    private Double xgPlusXagP90;
    @Column(name = "shots_p90")
    private Double shotsP90;
    @Column(name = "sot_p90")
    private Double sotP90;
    @Column(name = "offsides_p90")
    private Double offsidesP90;
    @Column(name = "fouls_p90")
    private Double foulsP90;
    @Column(name = "fouled_p90")
    private Double fouledP90;
    @Column(name = "clearances_p90")
    private Double clearancesP90;
    @Column(name = "interceptions_p90")
    private Double interceptionsP90;
    @Column(name = "tackles_p90")
    private Double tacklesP90;
    @Column(name = "tkl_plus_int_p90")
    private Double tklPlusIntP90;
    @Column(name = "tackles_won_p90")
    private Double tacklesWonP90;
    @Column(name = "dispossessed_p90")
    private Double dispossessedP90;
    @Column(name = "miscontrols_p90")
    private Double miscontrolsP90;
    @Column(name = "blocks_p90")
    private Double blocksP90;
    @Column(name = "errors_leading_shot_p90")
    private Double errorsLeadingShotP90;
    @Column(name = "recoveries_p90")
    private Double recoveriesP90;
    @Column(name = "aerial_won_p90")
    private Double aerialWonP90;
    @Column(name = "prog_carries_p90")
    private Double progCarriesP90;
    @Column(name = "prog_passes_p90")
    private Double progPassesP90;
    @Column(name = "prog_passes_received_p90")
    private Double progPassesReceivedP90;
    @Column(name = "passes_attempted_p90")
    private Double passesAttemptedP90;
    @Column(name = "take_on_attempted_p90")
    private Double takeOnAttemptedP90;
    @Column(name = "passes_completed_p90")
    private Double passesCompletedP90;
    @Column(name = "key_passes_p90")
    private Double keyPassesP90;
    @Column(name = "crosses_p90")
    private Double crossesP90;
    @Column(name = "switches_p90")
    private Double switchesP90;
    @Column(name = "through_balls_p90")
    private Double throughBallsP90;
    @Column(name = "gca_p90")
    private Double gcaP90;
    @Column(name = "sca_p90")
    private Double scaP90;
    @Column(name = "take_on_succ_p90")
    private Double takeOnSuccP90;
    @Column(name = "touches_p90")
    private Double touchesP90;
    @Column(name = "carries_p90")
    private Double carriesP90;
    @Column(name = "passes_received_p90")
    private Double passesReceivedP90;

    public Player() {
        // Questo costruttore è richiesto dalle specifiche di JPA/Hibernate
        // per permettere l'istanziazione tramite reflection.
    }
    
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public Integer getAge() { return age; }
    public void setAge(Integer age) { this.age = age; }

    public String getNation() { return nation; }
    public void setNation(String nation) { this.nation = nation; }

    public String getPosition() { return position; }
    public void setPosition(String position) { this.position = position; }

    public String getSquad() { return squad; }
    public void setSquad(String squad) { this.squad = squad; }

    public String getCompetition() { return competition; }
    public void setCompetition(String competition) { this.competition = competition; }
    
    public Integer getMatches() { return matches; }
    public void setMatches(Integer matches) { this.matches = matches; }

    public Integer getStarts() { return starts; }
    public void setStarts(Integer starts) { this.starts = starts; }

    public Integer getMinutes() { return minutes; }
    public void setMinutes(Integer minutes) { this.minutes = minutes; }

    public Double getNinetyS() { return ninetyS; }
    public void setNinetyS(Double ninetyS) { this.ninetyS = ninetyS; }

    public Integer getGoals() { return goals; }
    public void setGoals(Integer goals) { this.goals = goals; }

    public Integer getAssists() { return assists; }
    public void setAssists(Integer assists) { this.assists = assists; }

    public Integer getgPlusA() { return gPlusA; }
    public void setgPlusA(Integer gPlusA) { this.gPlusA = gPlusA; }

    public Integer getPkMade() { return pkMade; }
    public void setPkMade(Integer pkMade) { this.pkMade = pkMade; }

    public Integer getPkAttempted() { return pkAttempted; }
    public void setPkAttempted(Integer pkAttempted) { this.pkAttempted = pkAttempted; }

    public Integer getYellowCards() { return yellowCards; }
    public void setYellowCards(Integer yellowCards) { this.yellowCards = yellowCards; }

    public Integer getRedCards() { return redCards; }
    public void setRedCards(Integer redCards) { this.redCards = redCards; }

    public Double getXg() { return xg; }
    public void setXg(Double xg) { this.xg = xg; }

    public Double getNpxg() { return npxg; }
    public void setNpxg(Double npxg) { this.npxg = npxg; }

    public Double getXag() { return xag; }
    public void setXag(Double xag) { this.xag = xag; }

    public Double getNpxgPlusXag() { return npxgPlusXag; }
    public void setNpxgPlusXag(Double npxgPlusXag) { this.npxgPlusXag = npxgPlusXag; }

    public Integer getProgCarries() { return progCarries; }
    public void setProgCarries(Integer progCarries) { this.progCarries = progCarries; }

    public Integer getProgPasses() { return progPasses; }
    public void setProgPasses(Integer progPasses) { this.progPasses = progPasses; }

    public Integer getProgPassesReceived() { return progPassesReceived; }
    public void setProgPassesReceived(Integer progPassesReceived) { this.progPassesReceived = progPassesReceived; }

    public Double getXgPlusXag() { return xgPlusXag; }
    public void setXgPlusXag(Double xgPlusXag) { this.xgPlusXag = xgPlusXag; }

    public Double getAvgShotDist() { return avgShotDist; }
    public void setAvgShotDist(Double avgShotDist) { this.avgShotDist = avgShotDist; }

    public Double getgMinusXg() { return gMinusXg; }
    public void setgMinusXg(Double gMinusXg) { this.gMinusXg = gMinusXg; }

    public Double getgPerShots() { return gPerShots; }
    public void setgPerShots(Double gPerShots) { this.gPerShots = gPerShots; }

    public Double getgPerSot() { return gPerSot; }
    public void setgPerSot(Double gPerSot) { this.gPerSot = gPerSot; }

    public Integer getShots() { return shots; }
    public void setShots(Integer shots) { this.shots = shots; }

    public Integer getSot() { return sot; }
    public void setSot(Integer sot) { this.sot = sot; }

    public Double getSotPercentage() { return sotPercentage; }
    public void setSotPercentage(Double sotPercentage) { this.sotPercentage = sotPercentage; }

    public Double getNpgMinusXg() { return npgMinusXg; }
    public void setNpgMinusXg(Double npgMinusXg) { this.npgMinusXg = npgMinusXg; }

    public Double getNpxgPerShots() { return npxgPerShots; }
    public void setNpxgPerShots(Double npxgPerShots) { this.npxgPerShots = npxgPerShots; }

    public Integer getPassesFinalThird() { return passesFinalThird; }
    public void setPassesFinalThird(Integer passesFinalThird) { this.passesFinalThird = passesFinalThird; }

    public Double getaMinusXag() { return aMinusXag; }
    public void setaMinusXag(Double aMinusXag) { this.aMinusXag = aMinusXag; }

    public Integer getPassesAttempted() { return passesAttempted; }
    public void setPassesAttempted(Integer passesAttempted) { this.passesAttempted = passesAttempted; }

    public Integer getTakeOnAttempted() { return takeOnAttempted; }
    public void setTakeOnAttempted(Integer takeOnAttempted) { this.takeOnAttempted = takeOnAttempted; }

    public Integer getPassesCompleted() { return passesCompleted; }
    public void setPassesCompleted(Integer passesCompleted) { this.passesCompleted = passesCompleted; }

    public Double getPassesPercentage() { return passesPercentage; }
    public void setPassesPercentage(Double passesPercentage) { this.passesPercentage = passesPercentage; }

    public Integer getCrossesPenArea() { return crossesPenArea; }
    public void setCrossesPenArea(Integer crossesPenArea) { this.crossesPenArea = crossesPenArea; }

    public Integer getKeyPasses() { return keyPasses; }
    public void setKeyPasses(Integer keyPasses) { this.keyPasses = keyPasses; }

    public Integer getPassesPenArea() { return passesPenArea; }
    public void setPassesPenArea(Integer passesPenArea) { this.passesPenArea = passesPenArea; }

    public Double getTotDistPrgPasses() { return totDistPrgPasses; }
    public void setTotDistPrgPasses(Double totDistPrgPasses) { this.totDistPrgPasses = totDistPrgPasses; }

    public Double getTotDistPasses() { return totDistPasses; }
    public void setTotDistPasses(Double totDistPasses) { this.totDistPasses = totDistPasses; }

    public Integer getBlocks() { return blocks; }
    public void setBlocks(Integer blocks) { this.blocks = blocks; }

    public Integer getCornerKicks() { return cornerKicks; }
    public void setCornerKicks(Integer cornerKicks) { this.cornerKicks = cornerKicks; }

    public Integer getCrosses() { return crosses; }
    public void setCrosses(Integer crosses) { this.crosses = crosses; }

    public Integer getOffsides() { return offsides; }
    public void setOffsides(Integer offsides) { this.offsides = offsides; }

    public Integer getSwitches() { return switches; }
    public void setSwitches(Integer switches) { this.switches = switches; }

    public Integer getThroughBalls() { return throughBalls; }
    public void setThroughBalls(Integer throughBalls) { this.throughBalls = throughBalls; }

    public Integer getThrowIns() { return throwIns; }
    public void setThrowIns(Integer throwIns) { this.throwIns = throwIns; }

    public Integer getFouled() { return fouled; }
    public void setFouled(Integer fouled) { this.fouled = fouled; }

    public Integer getGca() { return gca; }
    public void setGca(Integer gca) { this.gca = gca; }

    public Integer getSca() { return sca; }
    public void setSca(Integer sca) { this.sca = sca; }

    public Integer getTacklesAtt3rd() { return tacklesAtt3rd; }
    public void setTacklesAtt3rd(Integer tacklesAtt3rd) { this.tacklesAtt3rd = tacklesAtt3rd; }

    public Integer getClearances() { return clearances; }
    public void setClearances(Integer clearances) { this.clearances = clearances; }

    public Integer getTacklesDef3rd() { return tacklesDef3rd; }
    public void setTacklesDef3rd(Integer tacklesDef3rd) { this.tacklesDef3rd = tacklesDef3rd; }

    public Integer getErrorsLeadingShot() { return errorsLeadingShot; }
    public void setErrorsLeadingShot(Integer errorsLeadingShot) { this.errorsLeadingShot = errorsLeadingShot; }

    public Integer getInterceptions() { return interceptions; }
    public void setInterceptions(Integer interceptions) { this.interceptions = interceptions; }

    public Integer getChallengesLost() { return challengesLost; }
    public void setChallengesLost(Integer challengesLost) { this.challengesLost = challengesLost; }

    public Integer getTacklesMid3rd() { return tacklesMid3rd; }
    public void setTacklesMid3rd(Integer tacklesMid3rd) { this.tacklesMid3rd = tacklesMid3rd; }

    public Integer getTackles() { return tackles; }
    public void setTackles(Integer tackles) { this.tackles = tackles; }

    public Double getTacklesPercentage() { return tacklesPercentage; }
    public void setTacklesPercentage(Double tacklesPercentage) { this.tacklesPercentage = tacklesPercentage; }

    public Integer getTklPlusInt() { return tklPlusInt; }
    public void setTklPlusInt(Integer tklPlusInt) { this.tklPlusInt = tklPlusInt; }

    public Integer getTacklesWon() { return tacklesWon; }
    public void setTacklesWon(Integer tacklesWon) { this.tacklesWon = tacklesWon; }

    public Integer getTouchesAttPen() { return touchesAttPen; }
    public void setTouchesAttPen(Integer touchesAttPen) { this.touchesAttPen = touchesAttPen; }

    public Integer getCarriesPenArea() { return carriesPenArea; }
    public void setCarriesPenArea(Integer carriesPenArea) { this.carriesPenArea = carriesPenArea; }

    public Integer getCarries() { return carries; }
    public void setCarries(Integer carries) { this.carries = carries; }

    public Integer getTouchesDefPen() { return touchesDefPen; }
    public void setTouchesDefPen(Integer touchesDefPen) { this.touchesDefPen = touchesDefPen; }

    public Integer getDispossessed() { return dispossessed; }
    public void setDispossessed(Integer dispossessed) { this.dispossessed = dispossessed; }

    public Integer getMiscontrols() { return miscontrols; }
    public void setMiscontrols(Integer miscontrols) { this.miscontrols = miscontrols; }

    public Integer getPassesReceived() { return passesReceived; }
    public void setPassesReceived(Integer passesReceived) { this.passesReceived = passesReceived; }

    public Integer getTakeOnSucc() { return takeOnSucc; }
    public void setTakeOnSucc(Integer takeOnSucc) { this.takeOnSucc = takeOnSucc; }

    public Double getTakeOnPercentage() { return takeOnPercentage; }
    public void setTakeOnPercentage(Double takeOnPercentage) { this.takeOnPercentage = takeOnPercentage; }

    public Integer getTouches() { return touches; }
    public void setTouches(Integer touches) { this.touches = touches; }

    public Integer getSecondYellow() { return secondYellow; }
    public void setSecondYellow(Integer secondYellow) { this.secondYellow = secondYellow; }

    public Integer getFouls() { return fouls; }
    public void setFouls(Integer fouls) { this.fouls = fouls; }

    public Integer getOwnGoal() { return ownGoal; }
    public void setOwnGoal(Integer ownGoal) { this.ownGoal = ownGoal; }

    public Integer getPkConceded() { return pkConceded; }
    public void setPkConceded(Integer pkConceded) { this.pkConceded = pkConceded; }

    public Integer getPkWon() { return pkWon; }
    public void setPkWon(Integer pkWon) { this.pkWon = pkWon; }

    public Integer getRecoveries() { return recoveries; }
    public void setRecoveries(Integer recoveries) { this.recoveries = recoveries; }

    public Integer getAerialWon() { return aerialWon; }
    public void setAerialWon(Integer aerialWon) { this.aerialWon = aerialWon; }

    public Double getAerialWonPercentage() { return aerialWonPercentage; }
    public void setAerialWonPercentage(Double aerialWonPercentage) { this.aerialWonPercentage = aerialWonPercentage; }

    public Integer getNpg() { return npg; }
    public void setNpg(Integer npg) { this.npg = npg; }

    public Double getGoalsP90() { return goalsP90; }
    public void setGoalsP90(Double goalsP90) { this.goalsP90 = goalsP90; }

    public Double getAssistsP90() { return assistsP90; }
    public void setAssistsP90(Double assistsP90) { this.assistsP90 = assistsP90; }

    public Double getgPlusAP90() { return gPlusAP90; }
    public void setgPlusAP90(Double gPlusAP90) { this.gPlusAP90 = gPlusAP90; }

    public Double getNpgP90() { return npgP90; }
    public void setNpgP90(Double npgP90) { this.npgP90 = npgP90; }

    public Double getXgP90() { return xgP90; }
    public void setXgP90(Double xgP90) { this.xgP90 = xgP90; }

    public Double getNpxgP90() { return npxgP90; }
    public void setNpxgP90(Double npxgP90) { this.npxgP90 = npxgP90; }

    public Double getXagP90() { return xagP90; }
    public void setXagP90(Double xagP90) { this.xagP90 = xagP90; }

    public Double getNpxgPlusXagP90() { return npxgPlusXagP90; }
    public void setNpxgPlusXagP90(Double npxgPlusXagP90) { this.npxgPlusXagP90 = npxgPlusXagP90; }

    public Double getXgPlusXagP90() { return xgPlusXagP90; }
    public void setXgPlusXagP90(Double xgPlusXagP90) { this.xgPlusXagP90 = xgPlusXagP90; }

    public Double getShotsP90() { return shotsP90; }
    public void setShotsP90(Double shotsP90) { this.shotsP90 = shotsP90; }

    public Double getSotP90() { return sotP90; }
    public void setSotP90(Double sotP90) { this.sotP90 = sotP90; }

    public Double getOffsidesP90() { return offsidesP90; }
    public void setOffsidesP90(Double offsidesP90) { this.offsidesP90 = offsidesP90; }

    public Double getFoulsP90() { return foulsP90; }
    public void setFoulsP90(Double foulsP90) { this.foulsP90 = foulsP90; }

    public Double getFouledP90() { return fouledP90; }
    public void setFouledP90(Double fouledP90) { this.fouledP90 = fouledP90; }

    public Double getClearancesP90() { return clearancesP90; }
    public void setClearancesP90(Double clearancesP90) { this.clearancesP90 = clearancesP90; }

    public Double getInterceptionsP90() { return interceptionsP90; }
    public void setInterceptionsP90(Double interceptionsP90) { this.interceptionsP90 = interceptionsP90; }

    public Double getTacklesP90() { return tacklesP90; }
    public void setTacklesP90(Double tacklesP90) { this.tacklesP90 = tacklesP90; }

    public Double getTklPlusIntP90() { return tklPlusIntP90; }
    public void setTklPlusIntP90(Double tklPlusIntP90) { this.tklPlusIntP90 = tklPlusIntP90; }

    public Double getTacklesWonP90() { return tacklesWonP90; }
    public void setTacklesWonP90(Double tacklesWonP90) { this.tacklesWonP90 = tacklesWonP90; }

    public Double getDispossessedP90() { return dispossessedP90; }
    public void setDispossessedP90(Double dispossessedP90) { this.dispossessedP90 = dispossessedP90; }

    public Double getMiscontrolsP90() { return miscontrolsP90; }
    public void setMiscontrolsP90(Double miscontrolsP90) { this.miscontrolsP90 = miscontrolsP90; }

    public Double getBlocksP90() { return blocksP90; }
    public void setBlocksP90(Double blocksP90) { this.blocksP90 = blocksP90; }

    public Double getErrorsLeadingShotP90() { return errorsLeadingShotP90; }
    public void setErrorsLeadingShotP90(Double errorsLeadingShotP90) { this.errorsLeadingShotP90 = errorsLeadingShotP90; }

    public Double getRecoveriesP90() { return recoveriesP90; }
    public void setRecoveriesP90(Double recoveriesP90) { this.recoveriesP90 = recoveriesP90; }

    public Double getAerialWonP90() { return aerialWonP90; }
    public void setAerialWonP90(Double aerialWonP90) { this.aerialWonP90 = aerialWonP90; }

    public Double getProgCarriesP90() { return progCarriesP90; }
    public void setProgCarriesP90(Double progCarriesP90) { this.progCarriesP90 = progCarriesP90; }

    public Double getProgPassesP90() { return progPassesP90; }
    public void setProgPassesP90(Double progPassesP90) { this.progPassesP90 = progPassesP90; }

    public Double getProgPassesReceivedP90() { return progPassesReceivedP90; }
    public void setProgPassesReceivedP90(Double progPassesReceivedP90) { this.progPassesReceivedP90 = progPassesReceivedP90; }

    public Double getPassesAttemptedP90() { return passesAttemptedP90; }
    public void setPassesAttemptedP90(Double passesAttemptedP90) { this.passesAttemptedP90 = passesAttemptedP90; }

    public Double getTakeOnAttemptedP90() { return takeOnAttemptedP90; }
    public void setTakeOnAttemptedP90(Double takeOnAttemptedP90) { this.takeOnAttemptedP90 = takeOnAttemptedP90; }

    public Double getPassesCompletedP90() { return passesCompletedP90; }
    public void setPassesCompletedP90(Double passesCompletedP90) { this.passesCompletedP90 = passesCompletedP90; }

    public Double getKeyPassesP90() { return keyPassesP90; }
    public void setKeyPassesP90(Double keyPassesP90) { this.keyPassesP90 = keyPassesP90; }

    public Double getCrossesP90() { return crossesP90; }
    public void setCrossesP90(Double crossesP90) { this.crossesP90 = crossesP90; }

    public Double getSwitchesP90() { return switchesP90; }
    public void setSwitchesP90(Double switchesP90) { this.switchesP90 = switchesP90; }

    public Double getThroughBallsP90() { return throughBallsP90; }
    public void setThroughBallsP90(Double throughBallsP90) { this.throughBallsP90 = throughBallsP90; }

    public Double getGcaP90() { return gcaP90; }
    public void setGcaP90(Double gcaP90) { this.gcaP90 = gcaP90; }

    public Double getScaP90() { return scaP90; }
    public void setScaP90(Double scaP90) { this.scaP90 = scaP90; }

    public Double getTakeOnSuccP90() { return takeOnSuccP90; }
    public void setTakeOnSuccP90(Double takeOnSuccP90) { this.takeOnSuccP90 = takeOnSuccP90; }

    public Double getTouchesP90() { return touchesP90; }
    public void setTouchesP90(Double touchesP90) { this.touchesP90 = touchesP90; }

    public Double getCarriesP90() { return carriesP90; }
    public void setCarriesP90(Double carriesP90) { this.carriesP90 = carriesP90; }

    public Double getPassesReceivedP90() { return passesReceivedP90; }
    public void setPassesReceivedP90(Double passesReceivedP90) { this.passesReceivedP90 = passesReceivedP90; }
}