// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.scouting.data.repository;

import com.scouting.data.model.Player;
import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Questa interfaccia rappresenta il nostro strato di accesso ai dati (Data Access Object Pattern).
 * Grazie a Spring Data JPA, non dobbiamo scrivere manualmente le query SQL; ci basta definire i metodi e il framework
 * genera l'implementazione a runtime (usando il Proxy Pattern).
 * <p>
 * Estendendo <code>JpaSpecificationExecutor</code>, abilitiamo la possibilità di passare oggetti complessi di tipo
 * <em>Specification</em> al metodo <code>findAll</code>. Questo è ciò che ci permette di tradurre i filtri dinamici
 * generati dalla nostra Factory in query SQL ottimizzate ed eseguite sul database H2 in memoria.
 */

@Repository
public interface PlayerRepository extends JpaRepository<Player, Long>, JpaSpecificationExecutor<Player> {

    List<Player> findByAgeBetween(Integer minAge, Integer maxAge);
    
    List<Player> findByPosition(String position);

    List<Player> findBySquad(String squad);

    List<Player> findByNation(String nation);

    List<Player> findByCompetition(String competition);
}