// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
 

package com.scouting.data.repository;

import com.scouting.data.model.Player;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface PlayerRepository extends JpaRepository<Player, Long> {
    // Non sono più necessari metodi findByAge, findBySquad, etc.
    // L'applicazione carica tutto in memoria nella Grid per US-02.
}